---
{% raw -%}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    resource_group_name: molecule
    virtual_network_name: molecule_vnet
    subnet_name: molecule_subnet
  tasks:
    - name: Destroy resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        force_delete_nonempty: true
        state: absent
      register: result

    # Mandatory configuration for Molecule to function.
    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: result is changed
{%- endraw %}
